### PR TITLE
Feat/report on location

### PR DESCRIPTION
**Pull request by j8seangel**
DONE: 
- [x] test properly in both systems (Android and iOS, the markers are sometimes keeping forever on the iOS map)
- [x] check with the design team the cancel icon.
- [x] disable onMapPress when pressing on the location marker.
- [x] fix crash when press the report here button

This PR includes the request on my location feature adding a marker in the middle of the screen while you drag the map.

Bonus: the header will show the alert coordinates

kapture 2018-05-31 at 18 33 00

### CODE REVIEW

**Comment by sorodrigo** [comment]
Looks great!!!! Just one detail, now that we removed onMapPress there's no way to unselect an alert when clicking on the map.

**Comment by j8seangel** [comment]
That was on purpose so you won't lose your selected alert unless you click in the same again.

**Comment by sorodrigo** [comment]
It’s not super clear, I wasn’t able to dismiss the selection 😪. Maybe a good solution is to add the remove button?

**Comment by j8seangel** [comment]
Button to cancel selection included!

**Pull request merged**
