### PR TITLE
Transifex

### PR DESCRIPTION
**Pull request by agnessa**
Adds a rake file to allow pushing the source file (EN) to transifex and pulling translations (ES, FR) into locale files. Pushing works differently depending on whether the resource already exists or not. In the latter case it is created, in the former it is updated, which will result in data loss if keys go missing from the source file.
```
cd ruby/transifex
bundle exec rake transifex:push
bundle exec rake transifex:pull
```

Locale files are now in JSON format, which makes replacing them easier. Therefore, a change in how locale files are loaded into the app was necessary.

### CODE REVIEW

**Comment by agnessa** [comment]
hang on, will move the API key elsewhere :dagger:

**Comment by geriux** [comment]
Thanks! maybe to the .env.sample file we use :)

**Comment by agnessa** [comment]
done, old api token revoked, sorry!

**Comment by geriux** [comment]
@agnessa Thank you so much for this! Gonna merge but can you please make another PR with some instructions to use this? Like, install this ruby version, install bundler, then bundle install, etc. Thanks!

**Pull request merged**
